name: owasp-dep-scan
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  dep_scan:
    name: Run dep Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Run dep Scan
      - uses: AppThreat/dep-scan-action@master
        with:
          # The target directory to be scanned. Optional.
          src: /github/workspace
          # Output file for the generated report. Optional.
          report_file: /github/workspace/reports/depscan.json
          # Must equal "I have sponsored OWASP-dep-scan" for action to run. Required.
          profile: generic
          thank_you: "I have not sponsored OWASP-dep-scan."
        env:
          VDB_HOME: ${{ github.workspace }}/db
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
